# Generated by Django 4.2.4 on 2024-01-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('artists', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=100)),
                ('spotify_url', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(max_length=200)),
            ],
        ),
    ]
