name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          cd ./server/music_discovery
          pip install -r requirements.txt

      - name: Run Migrations
        run: |
          cd ./server/music_discovery
          python manage.py migrate

      - name: Run Tests
        run: |
          cd ./server/music_discovery
          python manage.py test