name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          cd ./server
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Activate Virtual Environment
        run: |
          cd ./server
          .venv\Scripts\activate.bat

      - name: Run Migrations
        run: |
          cd ./server
          python manage.py migrate

      - name: Run Tests
        run: |
          cd ./server
          python manage.py test